version: "3" 
services:
  web_tandibi:
    image: alexrogna/tandibi_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_tandibi
      - .env/production/web_tandibi
    environment:
      - VIRTUAL_HOST=tandibi.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=tandibi.alexrogna.com
    networks:
      - proxy
    restart: always

  database_tandibi:
    image: postgis/postgis
    env_file:
      - .env/production/database_tandibi
    volumes:
      - db_data_tandibi:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_tandibi:
    image: alexrogna/tandibi_web:prod
    command: ["./wait-for", "--timeout=300", "database_tandibi:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_tandibi
      - .env/production/web_tandibi
    networks:
      - proxy
volumes:
  db_data_tandibi:
networks:
  proxy: